### ISSUE TITLE
Error line 101 Deploy.sh

### ISSUE THREAD

**Issue by rodrigorbonfim** [doitintl/iris3#16]
Hello, in the IRIS3 project, deploy.sh has an error on line 101, to correct the folder, replace the gcloud service list with the command below:
change:
done < <(gcloud services list | tail -n +2)

to: 
done < <(gcloud services list --format="value(config.name,config.title)")

**Comment by JoshuaFox** [comment]
Thank you! What sort of error message do you get?  Also, what do you mean by "folder" here?

I see that your `--format` approach is cleaner than taking `tail` to eliminate the header. And given we are doing that, the second field is `config.title`  not needed.  

I [have implemented ](https://github.com/doitintl/iris3/blob/884fd89d61fd7c51e279b5d81177d1e663f0a332/deploy.sh#L102)your recommendation, thanks again.

**Comment by rodrigorbonfim** [comment]
I had used Google Translate, I'm from Brazil and I don't speak English.

About "folder" was wrong translation, it would be "to fix the problem";

About the error message, unfortunately I don't have it anymore. I forgot to take a print.

**Comment by JoshuaFox** [comment]
No problem. Thank you for letting me know. How do you use Iris3? I am always interested in knowing how my open-source project is getting used. You can answer here, or if you prefer, please email me at `info @ joshuafox . com` (delete spaces)

**Comment by JoshuaFox** [comment]
The new `done < <(gcloud services list --format="value(config.name)")` as discussed, is  merged to `master`

**Comment by JoshuaFox** [comment]
The fix to 

`done < <(gcloud services list --format="value(config.name)")` 

, as discussed, is merged to master
