### ISSUE TITLE
why do you use GCP Pubsub

### ISSUE THREAD

**Issue by MaryLilian** [doitintl/iris3#17]
Hi, I am reading your project and I love this project
I have a question, why do you choose GCP Pubsub in your project instead of others like RabbitMQ or Kafka, are there any special features that others dont have it. Can you share me it. I am wondering when I should choose GCP Pubsub instead of others like RabbitMQ or Kafka

**Comment by JoshuaFox** [comment]
PubSub is available out-of-the-box in all Google Cloud projects, and is charged only by usage, and so is the easy choice.
