### ISSUE TITLE
No resources are being labeled

### ISSUE THREAD

**Issue by adickinson72** [doitintl/iris3#18]
I have a project that I've deployed to and the only change I've made from the default is to update the config.yaml to specify a single other specific project to get labeled for testing purposes that just has two buckets.

There are no errors when running `deploy.sh -c`
Neither bucket in my target project receives any labels.

I'm manually going into the Cloud Scheduler and selecting the `Force a job run` option
I see logs in the app engine showing:
```
textPayload: "INFO [] [Trace: bc6a996b4...5461;o=1] schedule() sent messages to label 1 projects, 1 messages"
textPayload: "INFO [] [Trace: bc6a996b4...5461;o=1] Time schedule(): 1162 ms"
```
A message also ends up in the `iris_deadletter` subscription

Any suggestions or method of debugging to help troubleshoot this better?

**Comment by JoshuaFox** [comment]
`iris_deadletter` -- interesting, I have not seen that before. 

I would 
* Check the `do_label` subscription that sends  messages to path `do_label`
* Trigger that path manually with a browser or curl
* Track this in logs. 
I would check that the message in the `iris_deadletter` subscription is this one. (Most likely it is. )

Could you email me at `info @ joshuafox . com` (without the spaces, of course) and I can debug it with you.

**Comment by adickinson72** [comment]
Issue was resolved by reinstalling in new project - unsure on original cause but most likely something failed to updated with a setting during subsequent deploys
