### ISSUE TITLE
Iris Labeller fails when it is unable to find a ephemeral GCP resource 

### ISSUE THREAD

**Issue by usaptos** [doitintl/iris3#21]
After deploying the labeller on GCP we ran into issue multiple times where the labeller would crash when it cant find a temporary or a ephemeral resource that no longer exists 
"nit__.py\", line 494, in api_request\\n    raise exceptions.from_http_response(response)\\ngoogle.api_core.exceptions.NotFound: 404 GET https://bigquery.googleapis.com/bigquery/v2/projects/analytics-test-345723/datasets/indexer_testnet_gcp_apps/tables/_sdc_current_token_pending_claims_staging?prettyPrint=false: Not found: Table analytics-test-345723:indexer_testnet_gcp_apps._sdc_current_token_pending_claims_staging","
Is there a way to avoid labelling resources temp in nature ?

**Comment by JoshuaFox** [comment]
Thank you for the bug report.

What would a solution look like? If we check that the resource exists before trying to label, the resource still might disappear before labeling.

Do you see problems with the  current approach, trying and sometimes failing (maybe with a nicer log)?

**Comment by JoshuaFox** [comment]
Discussed offline , and as mentioned above, it seems that the current behavior is not a problem,
