### ISSUE TITLE
Scheduled labeling does not work in projects in folders unless one specifies projects.

### ISSUE THREAD

**Issue by JoshuaFox** [doitintl/iris3#23]
There is a failure to label where all these are true:
* The  resource is in a project is in a folder (i.e, the bug does not occur if the project is directly in the org)
and
* The labeling is scheduled (by Cloud Scheduler) (i.e., the bug does not occur with labeling   that occurs on creation of resources).
and
* the `projects` config key (in `config.yaml` is empty `projects: []` (i.e., the bug does not occur if you have `projects: ['myproject']` 
 
Looking at the [code for listing projects](https://github.com/doitintl/iris3/blob/f851bab597716ed1091ac687c6573aa7b71caa76/main.py#L126), we see that if projects are not explicitly listed, `all_projects()`  [finds the projects ](https://github.com/doitintl/iris3/blob/f851bab597716ed1091ac687c6573aa7b71caa76/util/gcp_utils.py#L83)with [list_projects(parent=org_name)](https://cloud.google.com/python/docs/reference/cloudresourcemanager/latest/google.cloud.resourcemanager_v3.services.projects.ProjectsClient#google_cloud_resourcemanager_v3_services_projects_ProjectsClient_list_projects), which lists only the "projects that are direct children of the specified folder or organization resource".

 (As to why this issue was not earlier caught: It is probably because most labeling occurs on-creation, not with Cloud Scheduler. So, this issue would only be seen   for projects in a folder, and for existing resources labeled for the first time after Iris has been launched, or for Cloud SQL, or for disks whose attachment state has changed.)

 
The solution would be to use a combination of [list_folders](https://cloud.google.com/python/docs/reference/cloudresourcemanager/latest/google.cloud.resourcemanager_v3.services.folders.FoldersClient#google_cloud_resourcemanager_v3_services_folders_FoldersClient_list_folders) and the above-mentioned  `list_projects` to recursively walk the organization. It might make sense to parallelize the tree-walking algo. It might be best to return a Generator and have [get_enabled_projects](https://github.com/doitintl/iris3/blob/f851bab597716ed1091ac687c6573aa7b71caa76/main.py#L126) return a generator to better support cases with a huge number of projetcs, though if so, [sorting](https://github.com/doitintl/iris3/blob/f851bab597716ed1091ac687c6573aa7b71caa76/main.py#L142) will need to be removed -- and if we really have such a huge number of projects, we probably have bigger headaches.

**Comment by geekflyer** [comment]
heyho, wouldn't it be better/simpler to use Cloud Asset Inventory instead to get the list of projects? Afaik that automatically allows to recursively get the list of descendent projects within an organization or folder.

**Comment by JoshuaFox** [comment]
Great idea!  I gave this a try and it seems to give both projects in a folder and not.

```gcloud asset search-all-resources \
    --scope=organizations/<ORGID> \
    --asset-types=cloudresourcemanager.googleapis.com/Project
```

**Comment by JoshuaFox** [comment]
@geekflyer  I have implemented the feature. I used the Organizations/Folders API rather than Asset Inventory because Asset Inventory has a lag (and because it was not too hard to walk the folder tree)
