### ISSUE TITLE
allow user to create the custom role

### ISSUE THREAD

**Issue by JoshuaFox** [doitintl/iris3#8]
A  flag that can disable deploy.sh from attempting to create the custom role (the one named iris3), so that the user can pass in the name of an existing role

**Comment by pradeepaidtu** [comment]
Hi JoshuaFox,
How do you run deploy.sh script?

**Comment by JoshuaFox** [comment]
Hello, [Installation is described here](https://github.com/doitintl/iris3/blob/master/README.md#installation), including the running of `deploy.sh`.

Do you have any specific questions?

**Comment by JoshuaFox** [comment]
Not fixing this, as the user can easily do all this by editing the deployment scripts

**Comment by JoshuaFox** [comment]
Not fixing this, as the user can easily do all this by editing the deployment scripts

**Comment by JoshuaFox** [comment]
Not fixing this, as the user can easily do all this by editing the deployment scripts
